In [8]:
import sys
assert sys.version_info >= (3, 5)
import sklearn
assert sklearn.__version__ >= "0.20"
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix

import pandas as pd
import numpy as np
import os

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [12]:
# Modelos. Regresión logística (lr), Support Vector Machine (vc), K_means (k_means)

lr = LinearRegression(normalize=True)
vc = SVC(kernel='linear')
k_means = KMeans(n_clusters=5, random_state=42)

In [ ]:
# Carga y limpieza de datos

In [5]:
df_train = pd.read_csv(r'F:\Programacion\1.BOOTCAMP\data\general_dfs\mnist_train.csv')
df_test = pd.read_csv(r'F:\Programacion\1.BOOTCAMP\data\general_dfs\mnist_test.csv')

In [3]:
df_train.head(1)

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  

[1 rows x 785 columns]

In [5]:
df_test.head(1)

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  

[1 rows x 785 columns]

In [31]:
df_train.columns

Index(['label', '1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9',
       ...
       '28x19', '28x20', '28x21', '28x22', '28x23', '28x24', '28x25', '28x26',
       '28x27', '28x28'],
      dtype='object', length=785)

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to 28x28
dtypes: int64(785)
memory usage: 359.3 MB


In [8]:
df_train.isnull().any()

label    False
1x1      False
1x2      False
1x3      False
1x4      False
         ...  
28x24    False
28x25    False
28x26    False
28x27    False
28x28    False
Length: 785, dtype: bool

In [21]:
df_train['label'].value_counts()

1    6742
7    6265
3    6131
2    5958
9    5949
0    5923
6    5918
8    5851
4    5842
5    5421
Name: label, dtype: int64

In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 785 entries, label to 28x28
dtypes: int64(785)
memory usage: 59.9 MB


In [9]:
df_test.isnull().any()

label    False
1x1      False
1x2      False
1x3      False
1x4      False
         ...  
28x24    False
28x25    False
28x26    False
28x27    False
28x28    False
Length: 785, dtype: bool

In [ ]:
# Creación de modelos

In [6]:
X_train = df_train.iloc[:,1:]
y_train = df_train['label']

X_test = df_test.iloc[:,1:]
y_test = df_test['label']

In [88]:
# Regresión lineal

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)
y_pred = np.around(y_pred, 0).astype(int)
y_pred

array([6, 2, 2, ..., 8, 6, 6])

In [105]:
succ = (y_pred == y_test).value_counts()
print(succ,'\n\n',(2209*100/(7791+2209)),'%')

False    7791
True     2209
Name: label, dtype: int64 

 22.09 %


# kmeans

In [32]:
k_means.fit(X_train)
y_pred_k = k_means.predict(X_test)

In [33]:
y_pred_k

array([4, 1, 3, ..., 4, 3, 0])

In [34]:
k_means.cluster_centers_.shape

(5, 784)

In [35]:
y_pred_k is k_means.labels_

False

In [36]:
k_means.labels_

array([1, 2, 4, ..., 1, 0, 3])

In [40]:
succ = (y_pred_k == y_test).value_counts()
print(succ,'\n\n',(987*100/(9013+987)),'%')

False    9013
True      987
Name: label, dtype: int64 

 9.87 %


In [38]:
y_pred_k.shape, y_test.shape

((10000,), (10000,))

In [39]:
y_pred_k

array([4, 1, 3, ..., 4, 3, 0])