# Ejercicios de Numpy


In [1]:
print(3)
import numpy as np
print(4)

1) Create an array of 10 numbers

In [21]:
def gamma_ray (list_n, ranger, number):
    for e in range(ranger):
        list_n.append(number)
    list_n = np.array(list_n)
    return list_n

In [28]:
array_0 = []
array_0 = gamma_ray(array_0, 10, 0)
array_0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
array_1 = []
array_1 = gamma_ray(array_1, 10, 1)
array_1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
array_5 = []
array_5 = gamma_ray(array_5, 10, 5)
array_5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [31]:
array_10 = []
array_10 = gamma_ray(array_10, 10, 10)
array_10

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

2) create an array from 10 to 50 integrers

In [32]:
array_int = np.arange(10, 51)
array_int

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [33]:
array_even_int = np.arange(10, 50, 2)
array_even_int 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [34]:
array_3d = np.arange(0, 9).reshape(3, 3)
array_3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
identity_matrix = np.identity(3, dtype= float)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3) generate a random number using numpy

In [121]:
rand_num = np.array(np.random.randint(low= 0,  high= 2))
rand_num

array(0)

In [126]:
array_5d = np.array(np.random.normal(size= 25)).reshape(5, 5)
array_5d

array([[-0.6424159 ,  0.80831425, -0.68508615, -0.97543805, -0.95837141],
       [ 1.66200174, -0.39951638, -0.42071941,  0.5643684 ,  0.51217212],
       [ 0.62250014,  0.9618005 , -0.5919424 , -0.45977641,  0.58727843],
       [-0.17530569, -0.18291741,  1.02150388, -1.18689132,  1.69074574],
       [-1.88292488, -0.72356942, -0.51804292, -0.05011372,  0.64845293]])

In [128]:
strange_matrix = np.array(np.arange(1, 101)/100).reshape(10,10)
strange_matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [186]:
twenty_points =  np.sort(np.array(np.random.uniform(0,1., size=(4,5))), kind='mergesort', axis=0)
twenty_points
# WIP

array([[0.26879268, 0.01572626, 0.16722065, 0.15409327, 0.14525923],
       [0.36384757, 0.15284677, 0.27120272, 0.55605353, 0.33446148],
       [0.82704507, 0.65407326, 0.833975  , 0.6386349 , 0.42807817],
       [0.90226993, 0.97089936, 0.91559616, 0.75136148, 0.55530983]])

4) Duplicar resultados

In [219]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [221]:
# 1
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [222]:
mat.sum()

325

In [223]:
mat.std()

7.211102550927978

In [225]:
[sum(x) for x in zip(*mat)]

[55, 60, 65, 70, 75]

In [226]:
np.__version__

'1.16.5'