In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.base import BaseEstimator, TransformerMixin

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.model_selection import cross_val_score

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.datasets import make_classification

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

In [3]:
le = LabelEncoder()

In [4]:
path_1 = 'C:\\Users\\Servando\\Documents\\Project Hammer\\Datos\\enanos.csv'
path_2 = 'C:\\Users\\Servando\\Documents\\Project Hammer\\Datos\\elfos_oscuros.csv'


dwarfs = pd.read_csv(path_1, sep=';')
d_elves = pd.read_csv(path_2, sep=';')

print(f'{dwarfs.info()}\n{"-" * 10}\n{d_elves.info()}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         31 non-null     object 
 1   cod_unit     31 non-null     object 
 2   cod_faction  31 non-null     object 
 3   cod_spec     8 non-null      object 
 4   movement     31 non-null     int64  
 5   w_s          31 non-null     int64  
 6   b_s          31 non-null     int64  
 7   strenght     31 non-null     int64  
 8   toughness    31 non-null     int64  
 9   wounds       31 non-null     int64  
 10  initiative   31 non-null     int64  
 11  attacks      31 non-null     int64  
 12  leadership   31 non-null     int64  
 13  save         31 non-null     int64  
 14  equip_cod    0 non-null      float64
 15  cost         31 non-null     int64  
dtypes: float64(1), int64(11), object(4)
memory usage: 4.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data col

In [5]:
d_elves.head(1)

name cod_unit cod_faction  cod_spec  movement  w_s  b_s  \
0  Pr�ncipe Oscuro    LORDM       DELFS       NaN        12    7    6   

   strenght  toughness  wounds  initiative  attacks  leadership  save  \
0         4          3       3           8        4          10     0   

   equip_cod   cost  
0        NaN  125.0

In [31]:
whole = pd.concat([dwarfs, d_elves])
whole = whole.drop('cod_spec', axis= 1)
whole = whole.drop('equip_cod', axis= 1)
whole = whole.dropna()

whole.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65 entries, 0 to 35
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         65 non-null     object 
 1   cod_unit     65 non-null     object 
 2   cod_faction  65 non-null     object 
 3   movement     65 non-null     int64  
 4   w_s          65 non-null     int64  
 5   b_s          65 non-null     int64  
 6   strenght     65 non-null     int64  
 7   toughness    65 non-null     int64  
 8   wounds       65 non-null     int64  
 9   initiative   65 non-null     int64  
 10  attacks      65 non-null     int64  
 11  leadership   65 non-null     int64  
 12  save         65 non-null     int64  
 13  cost         65 non-null     float64
dtypes: float64(1), int64(10), object(3)
memory usage: 7.6+ KB


In [32]:
whole['cod_unit'] = le.fit_transform(whole['cod_unit'])
whole['cod_faction'] = le.fit_transform(whole['cod_faction'])

X = whole.iloc[:, 1 : -1]
y = whole['cost']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X_train.shape, y_train.shape

((43, 12), (43,))

In [8]:
linear = LinearRegression()
logistic = LogisticRegression()

In [39]:
lin_model = linear.fit(X_train, y_train)

y_pred = np.round(lin_model.predict(X_test))

m = confusion_matrix(y_test, y_pred)
print(m)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0

In [40]:
log_model = logistic.fit(X_train, y_train)

y_pred = np.round(logistic.predict(X_test))

m = confusion_matrix(y_test, y_pred)
print(m)

[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
F:\Python\Python\Python_39\lib\site-packages\sklearn\l