In [1]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical


In [2]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
network = models.Sequential()

In [6]:
network.add(layers.Dense(512,activation='relu', input_shape=(784,)))
network.add(layers.Dense(10, activation='softmax'))

In [7]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [8]:
network.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [9]:
train_images = train_images.reshape((60000,28*28))
test_images = test_images.reshape((10000,28*28))

In [11]:
train_images.shape

(60000, 784)

In [12]:
train_images= train_images.astype('float32')/255
test_images= test_images.astype('float32')/255

In [14]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [15]:
network.fit(train_images,train_labels, epochs=5, batch_size=128, validation_data=(test_images, test_labels))

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 107us/sample - loss: 0.2540 - accuracy: 0.9266 - val_loss: 0.1276 - val_accuracy: 0.9619
Epoch 2/5
60000/60000 [==============================] - 6s 103us/sample - loss: 0.1015 - accuracy: 0.9701 - val_loss: 0.0854 - val_accuracy: 0.9745
Epoch 3/5
60000/60000 [==============================] - 8s 128us/sample - loss: 0.0670 - accuracy: 0.9797 - val_loss: 0.0735 - val_accuracy: 0.9768
Epoch 4/5
60000/60000 [==============================] - 6s 95us/sample - loss: 0.0485 - accuracy: 0.9851 - val_loss: 0.0700 - val_accuracy: 0.9792
Epoch 5/5
60000/60000 [==============================] - 6s 105us/sample - loss: 0.0373 - accuracy: 0.9887 - val_loss: 0.0694 - val_accuracy: 0.9793


In [16]:
predictions = network.predict(test_images)

In [17]:
predictions.shape

(10000, 10)

In [18]:
predictions[1]

array([2.2181435e-13, 3.3547649e-06, 9.9999666e-01, 2.5823162e-08,
       1.6875981e-19, 3.6234911e-11, 1.4401127e-12, 4.5267552e-17,
       6.0177165e-09, 2.6654297e-17], dtype=float32)

In [22]:
np.argmax(predictions[1]), np.argmax(predictions[1])

(2, 2)

In [21]:
test_labels[1]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)